window.CATALOGUE_DATA = [
  {
    "title": "IAG SENTRY Armored Personnel Carrier",
    "ar_title": "IAG SENTRY ناقلة جنود مدرعة",
    "brand": "International Armored Group",
    "category": "Land Systems",
    "ar_category": "الأنظمة البرية",
    "filename": "iag-sentry-armored-personnel-carrier.pdf",
    "thumb": "iag-sentry-armored-personnel-carrier.jpg",
    "description": "Lightweight armored personnel carrier for patrol, reconnaissance and protected mobility.",
    "ar_description": "ناقلة جنود مدرعة خفيفة للدوريات والاستطلاع والتنقل المحمي.",
    "pages": "9",
    "available": true
  },
  {
    "title": "RILA 6x6-B Infantry Fighting Vehicle",
    "ar_title": "مركبة قتال المشاة RILA 6x6-B",
    "brand": "International Armored Group",
    "category": "Land Systems",
    "ar_category": "الأنظمة البرية",
    "filename": "rila-6x6-b-infantry-fighting-vehicle.pdf",
    "thumb": "rila-6x6-b-infantry-fighting-vehicle.jpg",
    "description": "High-mobility 6x6 infantry fighting vehicle platform.",
    "ar_description": "منصة قتال مشاة 6x6 عالية الحركة.",
    "pages": "2",
    "available": true
  },
  {
    "title": "RILA 8x8-A Infantry Fighting Vehicle",
    "ar_title": "مركبة قتال المشاة RILA 8x8-A",
    "brand": "International Armored Group",
    "category": "Land Systems",
    "ar_category": "الأنظمة البرية",
    "filename": "rila-8x8-a-infantry-fighting-vehicle.pdf",
    "thumb": "rila-8x8-a-infantry-fighting-vehicle.jpg",
    "description": "Protected 8x8 infantry fighting vehicle for demanding missions.",
    "ar_description": "مركبة قتال مشاة مدرعة 8x8 للمهام المتطلبة.",
    "pages": "2",
    "available": true
  },
  {
    "title": "Armored Anti-Riot Truck",
    "ar_title": "شاحنة مدرعة لمكافحة الشغب",
    "brand": "International Armored Group",
    "category": "Public Order Vehicles",
    "ar_category": "مركبات حفظ النظام",
    "filename": "armored-anti-riot-truck.pdf",
    "thumb": "armored-anti-riot-truck.jpg",
    "description": "Purpose-built protected vehicle for public-order and specialist response operations.",
    "ar_description": "مركبة محمية مخصصة لعمليات حفظ النظام والاستجابة المتخصصة.",
    "pages": "2",
    "available": true
  },
  {
    "title": "Armored Water Cannon",
    "ar_title": "مدرعة خراطيم المياه",
    "brand": "International Armored Group",
    "category": "Public Order Vehicles",
    "ar_category": "مركبات حفظ النظام",
    "filename": "armored-water-cannon.pdf",
    "thumb": "armored-water-cannon.jpg",
    "description": "Armored water-cannon vehicle for public order, firefighting and peacekeeping support.",
    "ar_description": "مركبة مدرعة بخراطيم مياه لحفظ النظام ومكافحة الحرائق ودعم حفظ السلام.",
    "pages": "2",
    "available": true
  },
  {
    "title": "PHAZZER Enforcer Overview",
    "ar_title": "نظرة عامة على PHAZZER Enforcer",
    "brand": "PHAZZER",
    "category": "Law Enforcement",
    "ar_category": "إنفاذ القانون",
    "filename": "phazzer-enforcer-overview.pdf",
    "thumb": "phazzer-enforcer-overview.jpg",
    "description": "Conducted-energy device platform and product comparison overview.",
    "ar_description": "منصة جهاز طاقة كهربائية مع نظرة مقارنة للمنتج.",
    "pages": "17",
    "available": true
  },
  {
    "title": "PHAZZER Enforcer Specifications",
    "ar_title": "مواصفات PHAZZER Enforcer",
    "brand": "PHAZZER",
    "category": "Law Enforcement",
    "ar_category": "إنفاذ القانون",
    "filename": "phazzer-enforcer-specifications.pdf",
    "thumb": "phazzer-enforcer-specifications.jpg",
    "description": "Full PHAZZER Enforcer comparison document including operating details, characteristics and technical specifications.",
    "ar_description": "المستند الكامل لمقارنة PHAZZER Enforcer، بما في ذلك تفاصيل التشغيل والخصائص والمواصفات الفنية.",
    "pages": "17",
    "available": true
  },
  {
    "title": "M300T Hearing Protector",
    "ar_title": "واقي السمع M300T",
    "brand": "EARMOR / OPSMEN",
    "category": "Tactical Equipment",
    "ar_category": "المعدات التكتيكية",
    "filename": "m300t-hearing-protector.pdf",
    "thumb": "m300t-hearing-protector.jpg",
    "description": "Bluetooth-enabled electronic hearing protection with situational awareness functions.",
    "ar_description": "حماية سمع إلكترونية مزودة بالبلوتوث ووظائف الوعي بالموقف.",
    "pages": "10",
    "available": true
  },
  {
    "title": "YF Protector Catalogue",
    "ar_title": "كتالوج YF Protector",
    "brand": "YF Protector",
    "category": "Protective Equipment",
    "ar_category": "معدات الحماية",
    "filename": "yf-protector-catalogue.pdf",
    "thumb": "yf-protector-catalogue.jpg",
    "description": "Ballistic and anti-riot personal protective equipment catalogue.",
    "ar_description": "كتالوج معدات الحماية الشخصية الباليستية ومكافحة الشغب.",
    "pages": "20",
    "available": true
  },
  {
    "title": "WOLFCOM Solutions Overview",
    "ar_title": "نظرة عامة على حلول WOLFCOM",
    "brand": "WOLFCOM",
    "category": "Surveillance & Evidence",
    "ar_category": "المراقبة وإدارة الأدلة",
    "filename": "wolfcom-solutions-overview.pdf",
    "thumb": "wolfcom-solutions-overview.jpg",
    "description": "Body-worn cameras, in-car video and digital evidence management solutions.",
    "ar_description": "كاميرات محمولة وأنظمة فيديو للمركبات وحلول إدارة الأدلة الرقمية.",
    "pages": "40",
    "available": true
  },
  {
    "title": "EDI-USA Tactical Catalogue 2026",
    "ar_title": "كتالوج EDI-USA التكتيكي 2026",
    "brand": "ExecDefense / EDI-USA",
    "category": "Protective Equipment",
    "ar_category": "معدات الحماية",
    "filename": "edi-usa-tactical-catalogue-2026.pdf",
    "thumb": "edi-usa-tactical-catalogue-2026.jpg",
    "description": "Body armor, helmets, shields, riot-control and tactical equipment.",
    "ar_description": "دروع وخوذ ودروع واقية ومعدات مكافحة الشغب والمعدات التكتيكية.",
    "pages": "17",
    "available": false
  },
  {
    "title": "T-3 Multifunctional Airsoft Baton",
    "ar_title": "عصا T-3 متعددة الوظائف",
    "brand": "Raysun",
    "category": "Less-Lethal & Rescue",
    "ar_category": "أقل فتكاً والإنقاذ",
    "filename": "t-3-multifunctional-airsoft-baton.pdf",
    "thumb": "t-3-multifunctional-airsoft-baton.jpg",
    "description": "CO2-powered multifunctional baton platform for approved law-enforcement applications.",
    "ar_description": "منصة عصا متعددة الوظائف تعمل بثاني أكسيد الكربون لتطبيقات إنفاذ القانون المعتمدة.",
    "pages": "1",
    "available": true
  },
  {
    "title": "Catch Me Net Gun",
    "ar_title": "قاذف الشبكة Catch Me",
    "brand": "Raysun",
    "category": "Less-Lethal & Rescue",
    "ar_category": "أقل فتكاً والإنقاذ",
    "filename": "catch-me-net-gun.pdf",
    "thumb": "catch-me-net-gun.jpg",
    "description": "Reusable net-deployment system for controlled capture applications.",
    "ar_description": "نظام قابل لإعادة الاستخدام لإطلاق الشبكات في تطبيقات السيطرة.",
    "pages": "1",
    "available": true
  },
  {
    "title": "APS Multifunctional Line Launcher",
    "ar_title": "قاذف الخطوط متعدد الوظائف APS",
    "brand": "Raysun",
    "category": "Rescue & Emergency",
    "ar_category": "الإنقاذ والطوارئ",
    "filename": "aps-multifunctional-line-launcher.pdf",
    "thumb": "aps-multifunctional-line-launcher.jpg",
    "description": "Pneumatic line and life-buoy launcher for rescue and deployment tasks.",
    "ar_description": "قاذف هوائي للخطوط وأطواق النجاة لمهام الإنقاذ والنشر.",
    "pages": "1",
    "available": true
  },
  {
    "title": "Cobra Cuffs Advantage",
    "ar_title": "مزايا Cobra Cuffs",
    "brand": "Milspec Plastics",
    "category": "Law Enforcement",
    "ar_category": "إنفاذ القانون",
    "filename": "cobra-cuffs-advantage.pdf",
    "thumb": "cobra-cuffs-advantage.jpg",
    "description": "Flexible double-lock restraint system product overview.",
    "ar_description": "نظرة عامة على نظام تقييد مرن مزدوج القفل.",
    "pages": "1",
    "available": true
  },
  {
    "title": "MKU Protection Systems",
    "ar_title": "أنظمة الحماية MKU",
    "brand": "MKU",
    "category": "Protective Equipment",
    "ar_category": "معدات الحماية",
    "filename": "mku-protection-systems.pdf",
    "thumb": "mku-protection-systems.jpg",
    "description": "Overview of advanced personal and platform protection capabilities.",
    "ar_description": "نظرة عامة على قدرات الحماية المتقدمة للأفراد والمنصات.",
    "pages": "8",
    "available": true
  },
  {
    "title": "Integrated Air & Missile Defence",
    "ar_title": "الدفاع الجوي والصاروخي المتكامل",
    "brand": "Leonardo",
    "category": "Air & Missile Defence",
    "ar_category": "الدفاع الجوي والصاروخي",
    "filename": "integrated-air-and-missile-defence.pdf",
    "thumb": "integrated-air-and-missile-defence.jpg",
    "description": "Multi-domain integrated air and missile defence capabilities.",
    "ar_description": "قدرات دفاع جوي وصاروخي متكاملة متعددة المجالات.",
    "pages": "8",
    "available": true
  },
  {
    "title": "ATOS Airborne Tactical Observation System",
    "ar_title": "نظام ATOS للمراقبة التكتيكية الجوية",
    "brand": "Leonardo",
    "category": "ISR & Surveillance",
    "ar_category": "الاستخبارات والمراقبة والاستطلاع",
    "filename": "atos-airborne-tactical-observation-system.pdf",
    "thumb": "atos-airborne-tactical-observation-system.jpg",
    "description": "Airborne mission system integrating sensors and subsystems for ISR missions.",
    "ar_description": "نظام مهام جوي يدمج المستشعرات والأنظمة الفرعية لمهام الاستطلاع والمراقبة.",
    "pages": "8",
    "available": true
  },
  {
    "title": "HITFIST 30 UL Remote Turret",
    "ar_title": "برج HITFIST 30 UL المتحكم به عن بعد",
    "brand": "Leonardo",
    "category": "Weapon Stations",
    "ar_category": "محطات التسليح",
    "filename": "hitfist-30-ul-remote-turret.pdf",
    "thumb": "hitfist-30-ul-remote-turret.jpg",
    "description": "Remote-controlled 30 mm turret with advanced fire-control and stabilized sights.",
    "ar_description": "برج 30 مم متحكم به عن بعد مع نظام متقدم لإدارة النيران ومناظير مثبتة.",
    "pages": "2",
    "available": true
  },
  {
    "title": "MIRACH 100/5 Aerial Target System",
    "ar_title": "نظام الهدف الجوي MIRACH 100/5",
    "brand": "Leonardo",
    "category": "Unmanned & Target Systems",
    "ar_category": "الأنظمة غير المأهولة والأهداف",
    "filename": "mirach-100-5-aerial-target-system.pdf",
    "thumb": "mirach-100-5-aerial-target-system.jpg",
    "description": "Reusable high-performance aerial target system for training and qualification.",
    "ar_description": "نظام هدف جوي عالي الأداء وقابل لإعادة الاستخدام للتدريب والتأهيل.",
    "pages": "2",
    "available": true
  },
  {
    "title": "ECOMAT-M Product Presentation",
    "ar_title": "عرض منتجات ECOMAT-M",
    "brand": "ECOMAT-M",
    "category": "Body Armour & Vests",
    "ar_category": "الدروع والسترات الواقية",
    "filename": "ecomat-m-product-presentation.pdf",
    "thumb": "ecomat-m-product-presentation.jpg",
    "description": "Individual ECOMAT-M ballistic T-shirts, police vests, concealable armour and tactical body-protection models.",
    "ar_description": "مجموعة منتجات الحماية الباليستية والدفاعية المتخصصة.",
    "pages": "37",
    "available": false
  },
  {
    "title": "ECOMAT-M Company Presentation",
    "ar_title": "عرض شركة ECOMAT-M",
    "brand": "ECOMAT-M",
    "category": "Defence Portfolio",
    "ar_category": "محفظة الدفاع",
    "filename": "ecomat-m-company-presentation.pdf",
    "thumb": "ecomat-m-company-presentation.jpg",
    "description": "Company capabilities in armament, ammunition, optics, vehicles, communications, radar, CBRN and training support.",
    "ar_description": "قدرات الشركة في معدات الدفاع والمركبات والاتصالات والدعم.",
    "pages": "32",
    "available": false
  },
  {
    "title": "Pito Aviation Product Brochure 2024",
    "ar_title": "كتيب منتجات Pito Aviation 2024",
    "brand": "Pito Aviation",
    "category": "Unmanned Systems",
    "ar_category": "الأنظمة غير المأهولة",
    "filename": "pito-aviation-product-brochure-2024.pdf",
    "thumb": "pito-aviation-product-brochure-2024.jpg",
    "description": "UAV and loitering-platform portfolio for surveillance and specialist missions.",
    "ar_description": "مجموعة طائرات غير مأهولة ومنصات جوالة للمراقبة والمهام المتخصصة.",
    "pages": "22",
    "available": true
  },
  {
    "title": "KINTEX Defence Catalogue",
    "ar_title": "كتالوج KINTEX الدفاعي",
    "brand": "KINTEX",
    "category": "Defence Portfolio",
    "ar_category": "محفظة الدفاع",
    "filename": "kintex-defence-catalogue.pdf",
    "thumb": "kintex-defence-catalogue.jpg",
    "description": "International defence equipment and technology portfolio.",
    "ar_description": "مجموعة دولية من معدات وتقنيات الدفاع.",
    "pages": "15",
    "available": true
  },
  {
    "title": "PHOBOS by SkyForce",
    "ar_title": "PHOBOS من SkyForce",
    "brand": "SkyForce",
    "category": "Unmanned Systems",
    "ar_category": "الأنظمة غير المأهولة",
    "filename": "phobos-by-skyforce.pdf",
    "thumb": "phobos-by-skyforce.jpg",
    "description": "Specialized unmanned aerial system product presentation.",
    "ar_description": "عرض منتج لنظام جوي غير مأهول متخصص.",
    "pages": "10",
    "available": true
  },
  {
    "title": "ASLON Ammunition Systems",
    "ar_title": "أنظمة الذخائر ASLON",
    "brand": "ASLON / MKE",
    "category": "Ammunition Systems",
    "ar_category": "أنظمة الذخائر",
    "filename": "aslon-ammunition-systems.pdf",
    "thumb": "aslon-ammunition-systems.jpg",
    "description": "Ammunition systems across multiple calibres and mission types.",
    "ar_description": "أنظمة ذخائر بمقاسات وأنواع مهام متعددة.",
    "pages": "32",
    "available": true
  },
  {
    "title": "ASLON Masks & Protective Equipment",
    "ar_title": "أقنعة ومعدات الحماية ASLON",
    "brand": "ASLON / MKE",
    "category": "CBRN & Protective Equipment",
    "ar_category": "معدات الحماية وCBRN",
    "filename": "aslon-masks-and-protective-equipment.pdf",
    "thumb": "aslon-masks-and-protective-equipment.jpg",
    "description": "Gas masks, canisters and CBRN personal protective equipment.",
    "ar_description": "أقنعة غاز ومرشحات ومعدات حماية شخصية كيميائية وبيولوجية وإشعاعية.",
    "pages": "16",
    "available": true
  },
  {
    "title": "ASLON Precision Rifles",
    "ar_title": "بنادق الدقة ASLON",
    "brand": "ASLON / MKE",
    "category": "Small Arms",
    "ar_category": "الأسلحة الخفيفة",
    "filename": "aslon-precision-rifles.pdf",
    "thumb": "aslon-precision-rifles.jpg",
    "description": "Precision-rifle product portfolio for authorized institutional customers.",
    "ar_description": "مجموعة بنادق دقة للعملاء المؤسسيين المصرح لهم.",
    "pages": "13",
    "available": true
  },
  {
    "title": "ASLON Pyrotechnics",
    "ar_title": "المواد البيروتقنية ASLON",
    "brand": "ASLON / MKE",
    "category": "Pyrotechnics",
    "ar_category": "المواد البيروتقنية",
    "filename": "aslon-pyrotechnics.pdf",
    "thumb": "aslon-pyrotechnics.jpg",
    "description": "Detonators, signalling, smoke and pyrotechnic products catalogue.",
    "ar_description": "كتالوج صواعق وإشارات ودخان ومنتجات بيروتقنية.",
    "pages": "26",
    "available": true
  },
  {
    "title": "ASLON Rocket Systems",
    "ar_title": "أنظمة الصواريخ ASLON",
    "brand": "ASLON / MKE",
    "category": "Rocket Systems",
    "ar_category": "أنظمة الصواريخ",
    "filename": "aslon-rocket-systems.pdf",
    "thumb": "aslon-rocket-systems.jpg",
    "description": "Rocket and propelling-system portfolio for authorized government requirements.",
    "ar_description": "مجموعة أنظمة صاروخية ودفع للمتطلبات الحكومية المصرح بها.",
    "pages": "11",
    "available": true
  },
  {
    "title": "ASLON Small Arms Ammunition",
    "ar_title": "ذخائر الأسلحة الخفيفة ASLON",
    "brand": "ASLON / MKE",
    "category": "Ammunition Systems",
    "ar_category": "أنظمة الذخائر",
    "filename": "aslon-small-arms-ammunition.pdf",
    "thumb": "aslon-small-arms-ammunition.jpg",
    "description": "Small-arms ammunition portfolio across common service calibres.",
    "ar_description": "مجموعة ذخائر أسلحة خفيفة بمقاسات خدمة شائعة.",
    "pages": "24",
    "available": true
  },
  {
    "title": "ASLON Small Arms",
    "ar_title": "الأسلحة الخفيفة ASLON",
    "brand": "ASLON / MKE",
    "category": "Small Arms",
    "ar_category": "الأسلحة الخفيفة",
    "filename": "aslon-small-arms.pdf",
    "thumb": "aslon-small-arms.jpg",
    "description": "Small-arms platform catalogue for authorized institutional customers.",
    "ar_description": "كتالوج منصات أسلحة خفيفة للعملاء المؤسسيين المصرح لهم.",
    "pages": "34",
    "available": true
  },
  {
    "title": "KONG Rescue Catalogue 2025",
    "ar_title": "كتالوج KONG للإنقاذ 2025",
    "brand": "KONG",
    "category": "Rescue & Emergency",
    "ar_category": "الإنقاذ والطوارئ",
    "filename": "kong-rescue-catalogue-2025.pdf",
    "thumb": "kong-rescue-catalogue-2025.jpg",
    "description": "Professional rescue, evacuation, lifting and helicopter-support equipment.",
    "ar_description": "معدات احترافية للإنقاذ والإخلاء والرفع ودعم المروحيات.",
    "pages": "43",
    "available": true
  },
  {
    "title": "KONG Tactical Catalogue",
    "ar_title": "كتالوج KONG التكتيكي",
    "brand": "KONG",
    "category": "Tactical Equipment",
    "ar_category": "المعدات التكتيكية",
    "filename": "kong-tactical-catalogue.pdf",
    "thumb": "kong-tactical-catalogue.jpg",
    "description": "Tactical helmets, harnesses, ropes, connectors, stretchers and access equipment.",
    "ar_description": "خوذ وأحزمة وحبال وموصلات ونقالات ومعدات وصول تكتيكية.",
    "pages": "56",
    "available": true
  },
  {
    "title": "Def-Tec Defense Product Manual",
    "ar_title": "دليل منتجات Def-Tec Defense",
    "brand": "Def-Tec Defense",
    "category": "Specialist Systems",
    "ar_category": "الأنظمة المتخصصة",
    "filename": "def-tec-defense-product-manual.pdf",
    "thumb": "def-tec-defense-product-manual.jpg",
    "description": "Specialist tactical systems, deployment products and mounting solutions.",
    "ar_description": "أنظمة تكتيكية متخصصة ومنتجات نشر وحلول تثبيت.",
    "pages": "61",
    "available": true
  },
  {
    "title": "Falcon 95 Unmanned Reconnaissance & Attack System",
    "ar_title": "نظام Falcon 95 للاستطلاع والهجوم غير المأهول",
    "brand": "Pito Aviation",
    "category": "Unmanned Systems",
    "ar_category": "الأنظمة غير المأهولة",
    "filename": "falcon-95-unmanned-reconnaissance-attack-system.pdf",
    "thumb": "falcon-95-unmanned-reconnaissance-attack-system.jpg",
    "description": "Twenty-page presentation covering the Falcon 95 unmanned reconnaissance and attack air vehicle system.",
    "ar_description": "عرض من عشرين صفحة حول نظام Falcon 95 الجوي غير المأهول للاستطلاع والهجوم.",
    "pages": "20",
    "available": true
  },
  {
    "title": "H-BAR Pop-Up Target System",
    "ar_title": "نظام الهدف المنبثق H-BAR",
    "brand": "LOMAH Target",
    "category": "Tactical Equipment",
    "ar_category": "المعدات التكتيكية",
    "filename": "h-bar-pop-up-target-system.pdf",
    "thumb": "h-bar-pop-up-target-system.jpg",
    "description": "Pop-up target and electronic scoring system for indoor and outdoor shooting-range training.",
    "ar_description": "نظام أهداف منبثقة وتسجيل إلكتروني للتدريب في ميادين الرماية الداخلية والخارجية.",
    "pages": "13",
    "available": true
  },
  {
    "title": "Leonardo Vehicle Systems",
    "ar_title": "Leonardo Vehicle Systems",
    "brand": "Leonardo",
    "category": "Land Systems",
    "ar_category": "Land Systems",
    "filename": "leonardo-vehicle-systems.pdf",
    "thumb": "leonardo-vehicle-systems.jpg",
    "description": "Vehicle C4I, communications, sights, fire control and protection systems.",
    "ar_description": "Vehicle C4I, communications, sights, fire control and protection systems.",
    "pages": "20",
    "available": true
  },
  {
    "title": "Dira Al Mustaqbal Company Profile",
    "ar_title": "الملف التعريفي لدرع المستقبل",
    "brand": "Dira Al Mustaqbal",
    "category": "Company Profile",
    "ar_category": "الملف التعريفي",
    "filename": "dira-al-mustaqbal-company-profile.pdf",
    "thumb": "dira-al-mustaqbal-company-profile.jpg",
    "description": "Company identity, contact details and bilingual corporate profile.",
    "ar_description": "الهوية المؤسسية وبيانات الاتصال والملف التعريفي باللغتين.",
    "pages": "3",
    "available": true
  },
  {
    "title": "Dragon Medical First Aid Kit Catalogue Rev.04",
    "ar_title": "كتالوج حقائب الإسعافات الأولية Dragon Medical",
    "brand": "Dragon Medical",
    "category": "EMS & Medical Response",
    "ar_category": "خدمات الطوارئ الطبية",
    "filename": "dragon-first-aid-kit-rev04.pdf",
    "thumb": "dragon-first-aid-kit-rev04.jpg",
    "description": "Emergency medical bags, personal first-aid kits, vehicle kits, medical boxes and EMS accessories.",
    "ar_description": "حقائب طبية للطوارئ ومجموعات إسعافات أولية ومستلزمات استجابة طبية.",
    "pages": "45",
    "available": true
  },
  {
    "title": "Dragon Medical Military First Aid Catalogue Rev.03",
    "ar_title": "كتالوج الإسعافات الأولية العسكرية Dragon Medical",
    "brand": "Dragon Medical",
    "category": "EMS & Medical Response",
    "ar_category": "خدمات الطوارئ الطبية",
    "filename": "dragon-military-first-aid-rev03.pdf",
    "thumb": "dragon-military-first-aid-rev03.jpg",
    "description": "Tactical medical bags, IFAKs, trauma consumables, stretchers and military field-care equipment.",
    "ar_description": "حقائب طبية تكتيكية ومجموعات إسعاف فردية ونقالات ومعدات رعاية ميدانية.",
    "pages": "28",
    "available": true
  },
  {
    "title": "RAYSUN N2.5 PepperJet Derringer",
    "ar_title": "RAYSUN N2.5 PepperJet Derringer",
    "brand": "RAYSUN",
    "category": "Law Enforcement",
    "ar_category": "إنفاذ القانون",
    "filename": "raysun-n25-pepperjet-derringer.pdf",
    "thumb": "raysun-n25-pepperjet-derringer.jpg",
    "description": "Compact less-lethal PepperJet product sheet.",
    "ar_description": "ورقة منتج لنظام PepperJet أقل فتكاً.",
    "pages": "1",
    "available": true
  },
  {
    "title": "V-great Products Catalogue 2024",
    "ar_title": "V-great Products Catalogue 2024",
    "brand": "V-great",
    "category": "Protective & Defence Equipment",
    "ar_category": "Protective & Defence Equipment",
    "filename": "v-great-products-catalogue-2024.pdf",
    "thumb": "v-great-products-catalogue-2024.jpg",
    "description": "Body armour, helmets, shields, EOD, tactical outfitting, emergency equipment and specialist vehicles.",
    "ar_description": "Body armour, helmets, shields, EOD, tactical outfitting, emergency equipment and specialist vehicles.",
    "pages": "53",
    "available": true
  },
  {
    "title": "EMN Defence Product Catalogue",
    "ar_title": "EMN Defence Product Catalogue",
    "brand": "EMN Defence",
    "category": "Defence Equipment",
    "ar_category": "Defence Equipment",
    "filename": "emn-defence-product-catalogue.pdf",
    "thumb": "emn-defence-product-catalogue.jpg",
    "description": "Helmets, protective equipment, small arms, optics, vehicles, UAVs and military systems.",
    "ar_description": "Helmets, protective equipment, small arms, optics, vehicles, UAVs and military systems.",
    "pages": "36",
    "available": true
  },
  {
    "title": "Blood-wing UMEX Product Portfolio",
    "ar_title": "Blood-wing UMEX Product Portfolio",
    "brand": "Blood-wing",
    "category": "Intelligent Soldier Systems",
    "ar_category": "Intelligent Soldier Systems",
    "filename": "blood-wing-umex-products.pdf",
    "thumb": "blood-wing-umex-products.jpg",
    "description": "Military augmented reality, robotics, exoskeletons and remote weapon-station technology.",
    "ar_description": "Military augmented reality, robotics, exoskeletons and remote weapon-station technology.",
    "pages": "10",
    "available": true
  }
];
