(() => {
 const data=Array.isArray(window.BRAND_DATA)?window.BRAND_DATA:[];
 const $=s=>document.querySelector(s), esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
 const media=src=>/^https?:\/\//i.test(String(src||''))?src:`assets/products/${src}`;
 const search=$('#manufacturerSearch'), grid=$('#manufacturerGrid'), empty=$('#manufacturerEmpty'), count=$('#manufacturerCount'); let status='all';
 $('#manufacturerTotal').textContent=data.length;
 function card(x){const verified=x.status==='official'; const label=verified?'Verified official website':x.status==='profile'?'Company profile':'Catalogue source'; const link=x.url?`<a class="manufacturer-link" href="${esc(x.url)}" target="_blank" rel="noopener">${verified?'Visit official website':'Open company profile'} ↗</a>`:`<span class="manufacturer-link disabled">Official public website not verified</span>`; return `<article class="manufacturer-card"><div class="manufacturer-image"><img src="${esc(media(x.image))}" alt="${esc(x.name)}" loading="lazy" onerror="this.onerror=null;this.src='${esc(media(x.fallback_image))}'"><span class="source-status ${esc(x.status)}">${label}</span></div><div class="manufacturer-copy"><p class="eyebrow">${esc(x.country)}</p><h2>${esc(x.name)}</h2><p>${esc(x.description)}</p><div class="manufacturer-meta"><span>${x.product_count} products</span><span>${x.sectors.length} sectors</span></div><div class="manufacturer-sectors">${x.sectors.slice(0,3).map(s=>`<a href="products.html?brand=${encodeURIComponent(x.name)}">${esc(s)}</a>`).join('')}</div>${link}<a class="browse-brand" href="products.html?brand=${encodeURIComponent(x.name)}">Browse products →</a></div></article>`}
 function render(){const q=search.value.trim().toLowerCase(); const list=data.filter(x=>(status==='all'||x.status===status)&&(!q||[x.name,x.country,x.description,...x.sectors].join(' ').toLowerCase().includes(q))); grid.innerHTML=list.map(card).join(''); count.textContent=`${list.length} of ${data.length} manufacturers`; grid.hidden=!list.length; empty.hidden=!!list.length;}
 search.addEventListener('input',render); document.querySelector('.manufacturer-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-status]');if(!b)return;status=b.dataset.status;document.querySelectorAll('[data-status]').forEach(x=>x.classList.toggle('active',x===b));render();}); render();
})();