(() => {
 const data=Array.isArray(window.PRODUCT_DATA)?window.PRODUCT_DATA:[], brands=Array.isArray(window.BRAND_DATA)?window.BRAND_DATA:[];
 const brandMap=Object.fromEntries(brands.map(x=>[x.name,x]));
 const $=s=>document.querySelector(s), esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
 const media=src=>/^https?:\/\//i.test(String(src||''))?String(src):`assets/products/${String(src||'')}`;
 const search=$('#productSearch'), solution=$('#sectorFilter'), category=$('#categoryFilter'), brand=$('#brandFilter'), sort=$('#sortFilter'), groups=$('#productGroups'), count=$('#productCount'), empty=$('#productEmpty');
 const unique=key=>[...new Set(data.map(x=>x[key]).filter(Boolean))].sort((a,b)=>a.localeCompare(b)); const allSolutions=[...new Set(data.flatMap(x=>[x.sector,...(x.solutions||[])]).filter(Boolean))].sort((a,b)=>a.localeCompare(b));
 const fill=(el,items)=>items.forEach(v=>el.insertAdjacentHTML('beforeend',`<option value="${esc(v)}">${esc(v)}</option>`)); fill(solution,allSolutions);fill(category,unique('category'));fill(brand,unique('brand')); $('#productTotal').textContent=data.length;
 const quick=['Helmets & Head Protection','Body Armour & Ballistic Protection','Clothing, Bags & Load-Carrying','Scopes, Thermal & Night Vision','Vehicles & Protected Mobility','UAV Platforms','EOD & Bomb Disposal','Training & Target Systems','Firefighting & Rescue','EMS & Medical Response','Rescue Access & Evacuation','Military & Law-Enforcement Firearms','Communications & Surveillance','Scanners, Cameras & Imaging','Boots & Professional Footwear'];
 $('#quickCategories').innerHTML=quick.map(v=>`<button type="button" data-solution="${esc(v)}">${esc(v)}</button>`).join('');
 const params=new URLSearchParams(location.search), valid=(el,v)=>[...el.options].some(o=>o.value===v);
 function applyParams(){search.value=params.get('q')||'';solution.value='all';category.value='all';brand.value='all'; const s=params.get('sector')||params.get('solution'),c=params.get('category'),b=params.get('brand');if(s&&valid(solution,s))solution.value=s;if(c&&valid(category,c))category.value=c;if(b&&valid(brand,b))brand.value=b;}
 const imageQueue=(x,src)=>{const raw=[src,...(x.image_candidates||[]),x.fallback_image,'system/product-unavailable.jpg'].filter(Boolean),seen=new Set();return raw.map(media).filter(v=>!seen.has(v)&&seen.add(v))};
 const img=(x,src,alt)=>{const q=imageQueue(x,src),first=q.shift()||media('system/product-unavailable.jpg');return `<img src="${esc(first)}" data-image-queue="${esc(q.join('|'))}" alt="${esc(alt)}" loading="lazy" referrerpolicy="no-referrer" onerror="const q=(this.dataset.imageQueue||'').split('|').filter(Boolean),n=q.shift();this.dataset.imageQueue=q.join('|');if(n){this.src=n}else{this.onerror=null}">`};
 let selected=new Set();
 function card(x){const official=x.brand_source_status==='official';return `<article class="product-card" tabindex="0" data-id="${esc(x.id)}"><div class="product-card-image">${img(x,x.image,x.title)}<span>${esc(x.brand)}</span>${official?'<b class="verified-badge">Official site</b>':''}${(x.gallery||[]).length>1?`<b class="card-gallery-badge">${x.gallery.length} images</b>`:''}</div><div class="product-card-copy"><p>${esc(x.category)}</p><h3>${esc(x.title)}</h3><div class="card-meta"><span>${esc(x.sector)}</span><button class="compare-toggle ${selected.has(x.id)?'active':''}" data-compare="${esc(x.id)}" type="button">${selected.has(x.id)?'✓ Selected':'+ Compare'}</button></div><span class="view-product">View product →</span></div></article>`}
 function filtered(){const q=search.value.trim().toLowerCase();let list=data.filter(x=>(solution.value==='all'||x.sector===solution.value||(x.solutions||[]).includes(solution.value))&&(category.value==='all'||x.category===category.value)&&(brand.value==='all'||x.brand===brand.value)&&(!q||x.search.toLowerCase().includes(q)));const s=sort.value;if(s==='az')list.sort((a,b)=>a.title.localeCompare(b.title));else if(s==='brand')list.sort((a,b)=>a.brand.localeCompare(b.brand)||a.title.localeCompare(b.title));else if(s==='category')list.sort((a,b)=>a.category.localeCompare(b.category)||a.title.localeCompare(b.title));return list;}
 const descriptions={Helmets:'Ballistic, tactical, rescue, riot and industrial head-protection systems.', 'UAV Platforms':'Fixed-wing, multirotor, VTOL, helicopter, tethered and heavy-lift unmanned platforms.', 'Body Armour & Vests':'Concealable, tactical, responder and specialist ballistic-protection systems.', 'Ballistic Shields':'Hand-carried, folding and mobile ballistic shields for specialist response.', 'Ballistic Plates':'Ceramic and UHMWPE hard-armour inserts for tactical carriers.', 'Stretchers':'Specialist rescue, helicopter, cave, mountain and confined-space patient transport.', 'Small Arms Ammunition':'Ammunition families organised by weapon class and operational application.', 'Training Targets':'Pop-up, live-fire and configurable range targets for indoor and outdoor training.', 'Electronic Scoring & Range Control':'Shooter monitors, central control, wireless communications and electronic score reporting.', 'Riot Protection Suits':'Public-order protective ensembles for police and security personnel.', 'Riot Shields':'Transparent and specialist public-order shields.', 'Unmanned Ground Systems':'Robotic ground platforms for inspection, reconnaissance and specialist missions.', 'Exoskeleton & Load Support':'Wearable powered systems designed to reduce fatigue and support sustained load carriage.', 'EMS Medical Bags':'Professional responder bags for organised emergency medical equipment.', 'First Aid Kits':'First-aid and casualty-care kits for field, fleet, workplace and personal use.', 'Tactical First Aid Kits':'Compact trauma kits and IFAKs for frontline emergency care.', 'EO/IR Cameras & Imaging':'Electro-optical and infrared cameras for day, night and all-weather observation.', 'Detection & Screening':'Portable and fixed systems for security screening, detection and inspection.', 'Body Cameras':'Body-worn video systems for evidence capture, live streaming and officer safety.', 'Military & Tactical Boots':'Military and tactical footwear organised by mission profile and construction.', 'Tactical Side-Zip Boots':'Rapid-entry side-zip footwear for law enforcement, security and response teams.', 'Flight & Deck Boots':'Aviation, flight-deck and safe-to-fly footwear.', 'Safety-Toe Boots':'Steel-toe and composite-toe footwear for protected industrial and operational use.', 'Waterproof & Insulated Boots':'Weather-protective footwear for wet, cold and demanding field conditions.', 'Jungle & Hot-Weather Boots':'Breathable hot-weather and jungle footwear for warm operating environments.', 'Training & Athletic Footwear':'Athletic, minimalist and training footwear for conditioning and duty use.', 'Duty & Dress Footwear':'Uniform, station and inspection-ready professional footwear.'};
 function render(){const list=filtered(),by={};list.forEach(x=>(by[x.category]??=[]).push(x));groups.innerHTML=Object.entries(by).sort(([a],[b])=>a.localeCompare(b)).map(([cat,items])=>`<section class="product-category-section"><div class="product-category-head"><div><p class="eyebrow">${esc(solution.value==='all'?items[0].sector:solution.value)}</p><h2>${esc(cat)}</h2><p>${esc(descriptions[cat]||`Browse ${cat.toLowerCase()} from ${new Set(items.map(x=>x.brand)).size} represented manufacturers.`)}</p></div><strong>${items.length}</strong></div><div class="product-grid-browser">${items.map(card).join('')}</div></section>`).join('');count.textContent=`${list.length} of ${data.length} products`;groups.hidden=!list.length;empty.hidden=!!list.length;}
 function sync(){const u=new URL(location.href);u.search='';if(search.value.trim())u.searchParams.set('q',search.value.trim());if(solution.value!=='all')u.searchParams.set('solution',solution.value);if(category.value!=='all')u.searchParams.set('category',category.value);if(brand.value!=='all')u.searchParams.set('brand',brand.value);history.replaceState(null,'',u);}
 [search,solution,category,brand,sort].forEach(el=>el.addEventListener(el===search?'input':'change',()=>{sync();render()}));$('#quickCategories').addEventListener('click',e=>{const b=e.target.closest('[data-solution]');if(!b)return;solution.value=b.dataset.solution;category.value='all';brand.value='all';search.value='';sync();render()});$('#clearFilters').addEventListener('click',()=>{search.value='';solution.value=category.value=brand.value='all';sort.value='featured';sync();render()});
 let gallery=[],gi=0,current=null;function show(i){if(!gallery.length)return;gi=(i+gallery.length)%gallery.length;const src=gallery[gi],q=imageQueue(current,src),modal=$('#modalImage');modal.onerror=()=>{q.shift();if(q.length)modal.src=q[0];else modal.onerror=null};modal.referrerPolicy='no-referrer';modal.src=q[0]||media('system/product-unavailable.jpg');$('#galleryCount').textContent=gallery.length>1?`${gi+1} / ${gallery.length}`:'';$('#galleryPrev').hidden=$('#galleryNext').hidden=gallery.length<2;$('#galleryThumbs').innerHTML=gallery.length>1?gallery.map((s,n)=>`<button data-gallery="${n}" class="${n===gi?'active':''}">${img(current,s,'')}</button>`).join(''):'';}
 function openProduct(x){current=x;gallery=(x.gallery||[]).length?x.gallery:[x.image];show(0);$('#modalTitle').textContent=x.title;$('#modalSector').textContent=x.solutions?.[0]||x.sector;$('#modalBrand').textContent=x.brand;$('#modalDescription').textContent=x.description;$('#modalCategory').textContent=x.category;$('#modalSource').textContent=x.source_title||x.brand;$('#modalPage').textContent=x.page||'—';$('#modalMediaCredit').textContent=x.media_credit||'Supplied manufacturer catalogue';const mediaLabel=x.visual_type==='illustrative'?'Illustrative catalogue render':(x.visual_type==='product-photography'?'Model-specific product photography':(x.official_media?'Official manufacturer media':'Manufacturer catalogue image'));$('#mediaBadge').textContent=mediaLabel;$('#mediaBadge').className=`official-media-badge ${x.official_media?'official':(x.visual_type==='illustrative'?'illustrative':'')}`;$('#modalTags').innerHTML=[...(x.tags||[]),...(x.solutions||[]).slice(0,2)].map(t=>`<span>${esc(t)}</span>`).join('');const msg=`Hello Dira Al Mustaqbal Trading, I would like information and a quotation for: ${x.title} (${x.brand}). Category: ${x.category}.`;$('#modalWhatsApp').href=`https://wa.me/97477889531?text=${encodeURIComponent(msg)}`;$('#modalEmail').href=`mailto:mahfz@hotmail.com?subject=${encodeURIComponent('Product enquiry: '+x.title)}&body=${encodeURIComponent(msg+'\n\nOfficial manufacturer reference: '+(x.source_url||x.brand_url||'Available on request'))}`;const off=$('#modalOfficial'),url=x.source_url||x.brand_url||brandMap[x.brand]?.url;off.hidden=!url;if(url)off.href=url;const related=data.filter(y=>y.id!==x.id&&y.category===x.category).slice(0,4);$('#relatedProducts').innerHTML=related.map(y=>`<button data-related="${esc(y.id)}">${img(y,y.image,y.title)}<span>${esc(y.title)}</span></button>`).join('');$('#productModal').hidden=false;document.body.classList.add('modal-open');}
 groups.addEventListener('click',e=>{const cb=e.target.closest('[data-compare]');if(cb){e.stopPropagation();toggleCompare(cb.dataset.compare);return;}const c=e.target.closest('.product-card');if(c)openProduct(data.find(x=>x.id===c.dataset.id))});groups.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('.product-card')){e.preventDefault();openProduct(data.find(x=>x.id===e.target.dataset.id))}});$('#galleryPrev').onclick=()=>show(gi-1);$('#galleryNext').onclick=()=>show(gi+1);$('#galleryThumbs').onclick=e=>{const b=e.target.closest('[data-gallery]');if(b)show(+b.dataset.gallery)};$('#relatedProducts').onclick=e=>{const b=e.target.closest('[data-related]');if(b)openProduct(data.find(x=>x.id===b.dataset.related))};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{$('#productModal').hidden=true;document.body.classList.remove('modal-open')});
 function toggleCompare(id){if(selected.has(id))selected.delete(id);else{if(selected.size>=3)return;selected.add(id)}updateCompare();render()}
 function updateCompare(){const list=[...selected].map(id=>data.find(x=>x.id===id)).filter(Boolean);$('#compareDrawer').hidden=!list.length;$('#compareCount').textContent=`${list.length} selected`;$('#compareMini').innerHTML=list.map(x=>`<span>${esc(x.title)}<button data-remove="${esc(x.id)}">×</button></span>`).join('');}
 $('#compareDrawer').addEventListener('click',e=>{const b=e.target.closest('[data-remove]');if(b){selected.delete(b.dataset.remove);updateCompare();render()}});$('#clearCompare').onclick=()=>{selected.clear();updateCompare();render()};$('#openCompare').onclick=()=>{const list=[...selected].map(id=>data.find(x=>x.id===id)).filter(Boolean);$('#compareTable').innerHTML=`<tr><th>Feature</th>${list.map(x=>`<th>${esc(x.title)}</th>`).join('')}</tr>${[['Company','brand'],['Solution','sector'],['Category','category'],['Description','description'],['Source','source_title']].map(([l,k])=>`<tr><th>${l}</th>${list.map(x=>`<td>${esc(x[k]||'—')}</td>`).join('')}</tr>`).join('')}`;$('#compareModal').hidden=false};document.querySelectorAll('[data-compare-close]').forEach(b=>b.onclick=()=>$('#compareModal').hidden=true);
 document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('#compareModal').hidden)$('#compareModal').hidden=true;else if(!$('#productModal').hidden){$('#productModal').hidden=true;document.body.classList.remove('modal-open')}}else if(!$('#productModal').hidden&&e.key==='ArrowLeft')show(gi-1);else if(!$('#productModal').hidden&&e.key==='ArrowRight')show(gi+1)});
 applyParams();render();
})();